# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.20.1
minecraft_version_range=[1.20,1.20.2)

# Forge
forge_id=forge
forge_version=47.4.23
forge_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

# Mod
mod_group_id=dev.xcolorful.cgcanimation
mod_id=cgcanimation
mod_name=CGC Animation Addon
mod_license=GPL-3.0-only
mod_version=26.10.23
mod_credits=Based on TaCZ and its contributors; continued by XiaoColorful
mod_authors=XiaoColorful
mod_description=Player animation addon for Custom Gun Continued

mod_issue_url=https://github.com/XColorful/CGC-Animation-Addon/issues
mod_display_url=https://github.com/XColorful/CGC-Animation-Addon/wiki
mod_logo_file=logo.png

pack_description=CGC Animation Addon resources
pack_format=15

# Mixin
mixin_config_file=cgcanimationclient.mixins.json
mixin_annotation=org.spongepowered:mixin:0.8.5:processor

# Dependencies
customgun_version_range=[26.10.23,)
customgun_maven=curse.maven:custom-gun-continued-1653554:9038440

player_animator_version_range=[1.0.1,)
player_animator_maven=curse.maven:playeranimator-658587:4587214

# CompileOnly
